import {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "CommentLayout Metadata",
  description: "Generated by create next app",
};

type Props = { children: ReactNode }
const CommentLayout = ({children}: Props) => {
    return (
        <div>
            <hr/>
            CommentLayout content
            {children}
            <hr/>
        </div>
    );
};
export default CommentLayout;