import {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Create A Car",
  description: "Generated by create next app",
};

type Props = { children: ReactNode }
const CreateCar = ({children}: Props) => {
    return (
        <div>
            <hr/>
            Create A Car
            {children}
            <hr/>
        </div>
    );
};
export default CreateCar;