import {Metadata} from "next";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "Post Info",
  description: "Generated by create next app",
};

type Props = { children: ReactNode }
const PostLayout = ({children}: Props) => {
    return (
        <div>
            <hr/>
            PostLayout content
            {children}
            <hr/>
        </div>
    );
};
export default PostLayout;